
#branches:
# only:
# - master
# - develop

language: objective-c
osx_image: xcode8.0

script:
  - xcodebuild -workspace Listenable.xcworkspace -scheme Listenable -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
