language: objective-c

branches:
 only:
 - master
 - develop

xcode_project: Listenable.xcodeproj
xcode_scheme: Listenable
osx_image: xcode8.2
xcode_sdk: iphonesimulator10.2

before_install:
  - cd ./Source

after_success:
  - bash <(curl -s https://codecov.io/bash)
