
language: objective-c
osx_image: xcode9

script:
  - xcodebuild -workspace Listenable.xcworkspace -scheme Listenable -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
