language: swift

branches:
 only:
 - master
 - develop

xcode_project: Listenable.xcodeproj
xcode_scheme: Listenable
osx_image: xcode8.0
xcode_sdk: iphonesimulator10.0

before_install:
  - cd ./Source

script:
  - xcodebuild -project Listenable.xcodeproj -scheme Listenable -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
