language: objective-c

branches:
 only:
 - master
 - develop

xcode_project: Listenable.xcodeproj
xcode_scheme: Listenable
osx_image: xcode8.2

before_install:
  - cd ./Source

script:
  - xcodebuild clean build test -project Listenable.xcodeproj -scheme Listenable

after_success:
  - bash <(curl -s https://codecov.io/bash)
